seed_ip: 172.16.101.1
username: 'cisco' # use environment var SC_USERNAME
password: 'cisco' # use env var SC_PASSWORD
max_devices: 500
output_dir: "./cli/home"
map_name: home_network
layout_algo: "rt"  # Optional, should be one of: kk, spring, circular, random
alternate_username: ''  # Optional
alternate_password: ''  # Optional
domain_name: ''  # Optional
exclude_string: ''  # Optional
timeout: 60  # Optional